import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../components/banner";
import Card from "../components/card";
import Layout from "../components/layout";
import { collection, query, getDocs, orderBy, limit } from "firebase/firestore";
import { db } from "../firebase";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [arr, setArr] = useState<any[]>([]);

  const getRanodomProperties = async () => {
    const q = query(
      collection(db, "property"),
      orderBy("numberOfReviews", "desc"),
      orderBy("totalStars", "desc"),
      limit(8)
    );
    console.log("--------------");
    const querySnapshot = await getDocs(q);
    setArr([]);
    querySnapshot.forEach((doc) => {
      setArr((prev) => [...prev, doc]);
    });
  };

  useEffect(() => {
    getRanodomProperties();
  }, []);
  return (
    <Layout>
      <Head>
        <title>mybnb</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Banner />
      </div>

      <div className="max-w-7xl mx-auto px-8 sm:px-16  ">
        <section className="pt-10">
          <div className="mb-10">
            <h2 className="pb-4">Get inspiration for your next trip </h2>
            <h3>Here are the most popular accomodations around the world</h3>
          </div>

          <div className="flex gap-4 flex-wrap">
            {arr.map((item) => {
              const property = item.data();
              const propertyid = item.id;
              return (
                <Card
                  key={propertyid}
                  propertyid={propertyid}
                  name={property.title}
                  description={""}
                  image={property.images[0]}
                  price={property.pricePerNight}
                  totalStars={property.totalStars}
                  numberOfReviews={property.numberOfReviews}
                  numberOfNights={0}
                />
              );
            })}
          </div>
        </section>
      </div>
    </Layout>
  );
};

export default Home;
