import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../components/banner";
import Card from "../components/card";
import Layout from "../components/layout";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>mybnb</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-7">
        <Banner />
      </div>

      <div className="max-w-7xl mx-auto px-8 sm:px-16  ">
        {/* grid place-items-center */}
        <section className="pt-5">
          <div className="">
            {/* ml-12 mt-10 -mb-7 */}
            <h2 className="pb-4">Explore cities</h2>
            <h3>Here are some of the most popular ones</h3>
          </div>
          <div className="flex overflow-x-scroll sm:overflow-auto">
            {/* sm:overflow-auto */}
            {/* overflow-scroll scrollbar-hide  */}
            {/* space-x-3 */}
            <Card
              // key="/images/app1.jpg"!!!!!!!!!!!!!!!!!!!!!!!!!
              // pri mapiranju ide blabal?.map.....!!!!!!!!!!!!!!!
              image="/images/app1.jpg"
              name="Beograd"
              description=""
              price="from 100"
            />
            <Card
              image="/images/app2.jpg"
              name="Kragujevac"
              description=""
              price="from 100"
            />
            <Card
              image="/images/app3.jpg"
              name="Novi Sad"
              description=""
              price="from 100"
            />
          </div>
        </section>
        <section className="pt-10">
          <div className="">
            <h2 className="pb-4">Get inspiration for your next trip </h2>
            <h3>Here are a few interesting accomodations</h3>
          </div>
          <div className="flex  overflow-x-scroll sm:overflow-auto ">
            {/* overflow-scroll scrollbar-hide  */}
            <Card
              image="/images/app1.jpg"
              name="New app"
              description="Modern 2 bedroom app, garage"
              price="100"
            />
            <Card
              image="/images/app2.jpg"
              name="New app"
              description="Modern 2 bedroom app, garage,"
              price="100"
            />
            <Card
              image="/images/app3.jpg"
              name="New app"
              description="Modern 2 bedroom app, garage"
              price="100"
            />
          </div>
        </section>
      </div>
    </Layout>
  );
};

export default Home;
